{% set name = "careamics" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/careamics-{{ version }}.tar.gz
  sha256: 0b83916f6fffb85dea251d0bcad33b13e8ebf643bd1b55128d88694c76b0e72c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy <2.0.0
    - pytorch >=2.0,<=2.6.0
    - torchvision <=0.21.0
    - bioimageio.core ==0.7
    - tifffile <=2025.3.13
    - psutil <=7.0.0
    - pydantic >=2.11,<=2.12
    - pytorch-lightning >=2.2,<=2.5.0.post0
    - pyyaml <=6.0.2,!=6.0.0
    - typer >=0.12.3,<=0.15.2
    - scikit-image <=0.25.2
    - zarr <3.0.0
    - pillow <=11.2.1
    - matplotlib-base <=3.10.1

    # Presumably this is only needed until the bioimageio.core pin is updated to v0.8.0
    - xarray <2025.3.0

test:
  imports:
    - careamics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://careamics.github.io
  summary: Deep-learning library for running N2V and friends.
  description: |
    CAREamics is a PyTorch library aimed at simplifying the use of Noise2Void and its many 
    variants and cousins (CARE, Noise2Noise, N2V2, P(P)N2V, HDN, MicroSplit etc.).
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/CAREamics/careamics
  doc_url: https://careamics.github.io
  doc_source_url: https://github.com/CAREamics/careamics.github.io

extra:
  recipe-maintainers:
    - jdeschamps
