{% set name = "careamics" %}
{% set version = "0.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/careamics-{{ version }}.tar.gz
  sha256: 7b246d8e967310dcea5bf9a99b4d1ec0ea732b6971b840ecb95cbc5dc17d8005

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0,<=2.4.6
    - pydantic >=2.11,<=2.13.3
    - pytorch-lightning >=2.2,<=2.6.5,!=2.6.2,!=2.6.3
    - pytorch >=2.0,<2.10.0
    - torchmetrics >0.11.0,<1.9.0
    - pyyaml <=6.0.3,!=6.0.0
    - scikit-image <=0.26.0
    - zarr >=3.0.0,<4.0.0
    - tifffile <=2026.3.3
    - matplotlib-base <=3.11.0
    - microssim <=0.0.4
    - torchvision <=0.25.0
    - bioimageio.core >=0.9.0,<=0.10.4
    - pillow <=12.2.0
    - psutil <=7.2.2


test:
  imports:
    - careamics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://careamics.github.io
  summary: Deep-learning library for running N2V and friends.
  description: |
    CAREamics is a PyTorch library aimed at simplifying the use of Noise2Void and its many 
    variants and cousins (CARE, Noise2Noise, N2V2, P(P)N2V, HDN, MicroSplit etc.).
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/CAREamics/careamics
  doc_url: https://careamics.github.io
  doc_source_url: https://github.com/CAREamics/careamics.github.io

extra:
  recipe-maintainers:
    - jdeschamps
